### ISSUE TITLE
403 Client Error: Forbidden for url: https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?limit=10

### ISSUE THREAD

**Issue by filipsPL** [jirikuchta/garmin-ical-export#1]
I have this issue. garmin-ical-export installed via pip3 today.

```python
Traceback (most recent call last):
  File "/home/filips/miniconda3/bin/garmin-ical-export", line 8, in <module>
    sys.exit(main())
  File "/home/filips/miniconda3/lib/python3.7/site-packages/garminicalexport/cmd.py", line 54, in main
    measurement_system=args.measurement_system)
  File "/home/filips/miniconda3/lib/python3.7/site-packages/garminicalexport/__init__.py", line 13, in to_ical
    activities_data = api.activites(limit, activity_type)
  File "/home/filips/miniconda3/lib/python3.7/site-packages/garminicalexport/garmin_api.py", line 42, in activites
    return get_activites(self.session, limit, activity_type)
  File "/home/filips/miniconda3/lib/python3.7/site-packages/garminicalexport/garmin_api.py", line 60, in get_activites
    res.raise_for_status()
  File "/home/filips/miniconda3/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?limit=10
```

**Comment by jirikuchta** [comment]
Didn't you misspelled your login email or password by any chance?

**Comment by filipsPL** [comment]
Thanks for your prompt reply! I don't think so, I've just copy-pasted login credentials from the console to the web form and successfully logged in...

Does it currently work for you? I've checked via web console that the API itself works fine...

**Comment by jirikuchta** [comment]
Yes, it does work for both of my accounts. 

Can you try it with this temporary account i've just created? 
```
garmin-ical-export yodapef430@flipssl.com Testicalexport1
```

**Comment by filipsPL** [comment]
Thanks. No, still doesn't work. I will try to fetch the code directly from github and play with it. Maybe some libraries at my side are outdated?

**Comment by filipsPL** [comment]
I've tested it (the pip version) on two other systems, and still doesn't work. Please note, in all three systems there is a miniconda python environment. Maybe this messing up somehow...

**Comment by jirikuchta** [comment]
You're right. I've tried it inside the miniconda and I'm getting the same error. I will try to find the cause and fix it later.

**Comment by jirikuchta** [comment]
Seems like the 403 status really comes from the Garmin server, but I can't manage to find why it is happening only in miniconda enviroment.

Both environments have the same version of python and requests library (and its dependency libraries). The requests being sent are just the same. Same user-agent, headers, cookies, IP address.

Since I can't see what is happening in the Garmin server and due to my lack of knowledge of miniconda, I run out of ideas how to tackle this issue.

The only solution I can give you is to install and run the the library outside miniconda.

**Comment by filipsPL** [comment]
Thanks for investigating this. Really strange! I will install it outside my conda evironments. Thanks!
