### ISSUE TITLE
403 Client error from 25/9

### ISSUE THREAD

**Issue by KrickGregory** [jirikuchta/garmin-ical-export#3]
Dear,

I use the program on 3 computers and since 25/9 I get 403 error. Login and pass is surely correct. Think Garmin changed something. Thanks for looking at this. And many, many, many thanks for your code. Use it everyday.

Traceback (most recent call last):
  File "/home/gregory/.local/bin/garmin-ical-export", line 8, in <module>
    sys.exit(main())
  File "/home/gregory/.local/lib/python3.10/site-packages/garminicalexport/cmd.py", line 52, in main
    ical = to_ical(login_data, args.limit,
  File "/home/gregory/.local/lib/python3.10/site-packages/garminicalexport/__init__.py", line 13, in to_ical
    activities_data = api.activites(limit, activity_type)
  File "/home/gregory/.local/lib/python3.10/site-packages/garminicalexport/garmin_api.py", line 42, in activites
    return get_activites(self.session, limit, activity_type)
  File "/home/gregory/.local/lib/python3.10/site-packages/garminicalexport/garmin_api.py", line 60, in get_activites
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?limit=1

Kind regards.

**Comment by m4lvin** [comment]
I run into the same.

When I use the firefox browser (where I am logged into connect) to access https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?limit=10000 (or any lower number at the end) then interestingly I do not get a `403` but a `402` error that means `Payment Required` :crying_cat_face: [according  to mdn](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/402).

Other research:
- A discussion in the Garmin developer forum about setting the right headers, two years old: https://forums.garmin.com/apps-software/mobile-apps-web/f/garmin-connect-web/286590/connect-api---activity-list-payment-required

**Comment by matin** [comment]
This is related to the same issue discussed in https://github.com/pe-st/garmin-connect-export/issues/95. The issue can be resolved by migrating to [Garth](https://github.com/matin/garth) for the authentication.

The discussion includes several examples of projects that performed the migration.

**Comment by KrickGregory** [comment]
Hey,

Can't succeed in installing garth. Everything went ok but fails after 
import garthth
from getpass import getpass

Isn't there a way to change code of garmin-ical-exporter because that's all I use. I'm not an It-guy so my knowledge is not that big of coding.

Kind regards.

**Comment by jirikuchta** [comment]
Hi,

Garmin seems to have tightened their Clouflare protection causing the script to fail to login. After a couple of attempts to solve this on my own I finally decided to let the [Garth](https://github.com/matin/garth)  to handle the login process as @matin suggested.

Upgrade to latest version (`pip install --upgrade garmin-ical-export`) and everything should work again.

Thank you for bug report and sorry for late response.

**Comment by KrickGregory** [comment]
OOOOH It works again. I could kiss you :-) 
So gratefull, thanks.
