### ISSUE TITLE
No activities - need user agent fix from newer garth?

### ISSUE THREAD

**Issue by m4lvin** [jirikuchta/garmin-ical-export#4]
I kept getting an empty ical file because the garmin API result contained no activities.

With the fix from here https://github.com/matin/garth/issues/73 it works again.

I am unsure how to fix this. Does the package here depend on a specific `garth` version?

**Comment by jirikuchta** [comment]
I guess you just have to reinstall the package to update the garth version. 

Try `pip install --upgrade --force-reinstall garmin-ical-export`.

**Comment by m4lvin** [comment]
Okay, thank you, it worked.

For the record, if other use `pipx`:

```
pipx uninstall garmin-ical-export
pipx install garmin-ical-export
pipx inject garmin-ical-export pytz
```

The last line is there to get rid of a warning about `pytz` missing.
